[package]
name = "wifi-password"
version = "0.1.2"
authors = ["Joslin, Brady W (Brady) <brady@bradyjoslin.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
qrcode = { version = "0.12", default-features = false }