[package]
authors = ["Joslin, Brady W (Brady) <brady@bradyjoslin.com>"]
edition = "2018"
name = "sharewifi"
version = "0.1.8"

[dependencies]
qrcode = {version = "0.12", default-features = false}
structopt = "0.3"
run_script = "0.9.0"
regex = "1.5.5"