[package]
authors = ["Joslin, Brady W (Brady) <brady@bradyjoslin.com>"]
edition = "2018"
name = "sharewifi"
version = "0.1.4"

[dependencies]
qrcode = {version = "0.12", default-features = false}
structopt = "0.3"
